pyscript:
  apps: 
    ruuvi-gateway:
      mqtt_topic_prefix: ruuvi
      ruuvitags:
        f33d5fc20393: Living Room Ruuvitag
        ec757cb84337: Bedroom Ruuvitag
        fc2c231a4b24: Kitchen Ruuvitag
        e86561efa878: Garage Ruuvitag
      measurements:
        temperature:
          config:
            stat_t: homeassistant/sensor/<MAC>/temperature/state
            json_attr_t: homeassistant/sensor/<MAC>/temperature/attributes
            name: <TAG_NAME> Temperature
            unit_of_meas: "\u00b0F"
            dev_cla: temperature
            uniq_id: ruuvitag_<MAC>_temperature
            device:
              ids: ruuvitag-<MAC>
              mf: Ruuvi Innovations Ltd
              mdl: RuuviTag
              name: <TAG_NAME>
          attributes:
            Ruuvitag: <MAC>
            Measure: Temperature
            Unit: "\u00b0F"
          transform: 
            expression: (<VALUE>*(9/5))+32
          source_metric: temperature
          precision: 2
        humidity:
          config:
            stat_t: homeassistant/sensor/<MAC>/humidity/state
            json_attr_t: homeassistant/sensor/<MAC>/humidity/attributes
            name: <TAG_NAME> Humidity
            unit_of_meas: '%'
            dev_cla: humidity
            uniq_id: ruuvitag_<MAC>_humidity
            device:
              ids: ruuvitag-<MAC>
              mf: Ruuvi Innovations Ltd
              mdl: RuuviTag
              name: <TAG_NAME>
          attributes:
            Ruuvitag: <MAC>
            Measure: Humidity
            Unit: '%'
          source_metric: humidity
          precision: 2
        battery_level:
          config:
            stat_t: homeassistant/sensor/<MAC>/battery_level/state
            json_attr_t: homeassistant/sensor/<MAC>/battery_level/attributes
            name: <TAG_NAME> Battery Level
            unit_of_meas: '%'
            dev_cla: battery
            uniq_id: ruuvitag_<MAC>_battery_level
            device:
              ids: ruuvitag-<MAC>
              mf: Ruuvi Innovations Ltd
              mdl: RuuviTag
              name: <TAG_NAME>
          attributes:
            Ruuvitag: <MAC>
            Measure: Battery Level
            Unit: '%'
          transform: 
            expression: ((<VALUE> - 2500) / (3000 - 2500)) * 100
            min_val: 0
            max_val: 100
          source_metric: battery
          precision: 0
        pressure:
          config:
            stat_t: homeassistant/sensor/<MAC>/pressure/state
            json_attr_t: homeassistant/sensor/<MAC>/pressure/attributes
            name: <TAG_NAME> Pressure
            unit_of_meas: hPa
            dev_cla: pressure
            uniq_id: ruuvitag_<MAC>_pressure
            device:
              ids: ruuvitag-<MAC>
              mf: Ruuvi Innovations Ltd
              mdl: RuuviTag
              name: <TAG_NAME>
          attributes:
            Ruuvitag: <MAC>
            Measure: Pressure
            Unit: hPa
          source_metric: pressure
          precision: 2
        tx_power:
          config:
            stat_t: homeassistant/sensor/<MAC>/tx_power/state
            json_attr_t: homeassistant/sensor/<MAC>/tx_power/attributes
            name: <TAG_NAME> Tx Power
            unit_of_meas: dBm
            dev_cla: signal_strength
            uniq_id: ruuvitag_<MAC>_tx_power
            device:
              ids: ruuvitag-<MAC>
              mf: Ruuvi Innovations Ltd
              mdl: RuuviTag
              name: <TAG_NAME>
          attributes:
            Ruuvitag: <MAC>
            Measure: Tx Power
            Unit: dBm
          source_metric: tx_power
        rssi:
          config:
            stat_t: homeassistant/sensor/<MAC>/rssi/state
            json_attr_t: homeassistant/sensor/<MAC>/rssi/attributes
            name: <TAG_NAME> RSSI
            unit_of_meas: dBm
            dev_cla: signal_strength
            uniq_id: ruuvitag_<MAC>_rssi
            device:
              ids: ruuvitag-<MAC>
              mf: Ruuvi Innovations Ltd
              mdl: RuuviTag
              name: <TAG_NAME>
          attributes:
            Ruuvitag: <MAC>
            Measure: RSSI
            Unit: dBm
          source_metric: rssi
  